#! /usr/bin/env python

"""Non-terminal symbols of Python grammar (from "graminit.h")."""

#  This file is automatically generated; please don't muck it up!
#
#  To update the symbols in this file, 'cd' to the top directory of
#  the python source tree after building the interpreter and run:
#
#    ./python Lib/symbol.py

#--start constants--
single_input = 256
file_input = 257
eval_input = 258
decorator = 259
decorators = 260
decorated = 261
async_funcdef = 262
funcdef = 263
parameters = 264
typedargslist = 265
tname = 266
tfpdef = 267
tfplist = 268
varargslist = 269
vname = 270
vfpdef = 271
vfplist = 272
stmt = 273
simple_stmt = 274
small_stmt = 275
expr_stmt = 276
augassign = 277
print_stmt = 278
del_stmt = 279
pass_stmt = 280
flow_stmt = 281
break_stmt = 282
continue_stmt = 283
return_stmt = 284
yield_stmt = 285
raise_stmt = 286
import_stmt = 287
import_name = 288
import_from = 289
import_as_name = 290
dotted_as_name = 291
import_as_names = 292
dotted_as_names = 293
dotted_name = 294
global_stmt = 295
nonlocal_stmt = 296
exec_stmt = 297
assert_stmt = 298
compound_stmt = 299
async_stmt = 300
if_stmt = 301
while_stmt = 302
for_stmt = 303
try_stmt = 304
with_stmt = 305
with_item = 306
except_clause = 307
suite = 308
testlist_safe = 309
old_test = 310
old_lambdef = 311
test = 312
or_test = 313
and_test = 314
not_test = 315
comparison = 316
comp_op = 317
expr = 318
xor_expr = 319
and_expr = 320
shift_expr = 321
arith_expr = 322
term = 323
factor = 324
power = 325
atom_expr = 326
atom = 327
listmaker = 328
testlist_comp = 329
lambdef = 330
trailer = 331
subscriptlist = 332
subscript = 333
sliceop = 334
exprlist = 335
testlist = 336
dictorsetmaker = 337
classdef = 338
arglist = 339
argument = 340
list_iter = 341
list_for = 342
list_if = 343
comp_iter = 344
comp_for = 345
comp_if = 346
testlist1 = 347
encoding_decl = 348
yield_expr = 349
yield_arg = 350
#--end constants--

sym_name = {}
for _name, _value in globals().items():
    if type(_value) is type(0):
        sym_name[_value] = _name


def main():
    import sys
    import token
    if len(sys.argv) == 1:
        sys.argv = sys.argv + ["Include/graminit.h", "Lib/symbol.py"]
    token.main()

if __name__ == "__main__":
    main()
