/* Generated by Parser/pgen */

#include "pgenheaders.h"
#include "grammar.h"
PyAPI_DATA(grammar) _PyParser_Grammar;
static arc arcs_0_0[3] = {
    {2, 1},
    {3, 1},
    {4, 2},
};
static arc arcs_0_1[1] = {
    {0, 1},
};
static arc arcs_0_2[1] = {
    {2, 1},
};
static state states_0[3] = {
    {3, arcs_0_0},
    {1, arcs_0_1},
    {1, arcs_0_2},
};
static arc arcs_1_0[3] = {
    {2, 0},
    {6, 0},
    {7, 1},
};
static arc arcs_1_1[1] = {
    {0, 1},
};
static state states_1[2] = {
    {3, arcs_1_0},
    {1, arcs_1_1},
};
static arc arcs_2_0[1] = {
    {9, 1},
};
static arc arcs_2_1[2] = {
    {2, 1},
    {7, 2},
};
static arc arcs_2_2[1] = {
    {0, 2},
};
static state states_2[3] = {
    {1, arcs_2_0},
    {2, arcs_2_1},
    {1, arcs_2_2},
};
static arc arcs_3_0[1] = {
    {11, 1},
};
static arc arcs_3_1[1] = {
    {12, 2},
};
static arc arcs_3_2[2] = {
    {13, 3},
    {2, 4},
};
static arc arcs_3_3[2] = {
    {14, 5},
    {15, 6},
};
static arc arcs_3_4[1] = {
    {0, 4},
};
static arc arcs_3_5[1] = {
    {15, 6},
};
static arc arcs_3_6[1] = {
    {2, 4},
};
static state states_3[7] = {
    {1, arcs_3_0},
    {1, arcs_3_1},
    {2, arcs_3_2},
    {2, arcs_3_3},
    {1, arcs_3_4},
    {1, arcs_3_5},
    {1, arcs_3_6},
};
static arc arcs_4_0[1] = {
    {10, 1},
};
static arc arcs_4_1[2] = {
    {10, 1},
    {0, 1},
};
static state states_4[2] = {
    {1, arcs_4_0},
    {2, arcs_4_1},
};
static arc arcs_5_0[1] = {
    {16, 1},
};
static arc arcs_5_1[3] = {
    {18, 2},
    {19, 2},
    {20, 2},
};
static arc arcs_5_2[1] = {
    {0, 2},
};
static state states_5[3] = {
    {1, arcs_5_0},
    {3, arcs_5_1},
    {1, arcs_5_2},
};
static arc arcs_6_0[1] = {
    {21, 1},
};
static arc arcs_6_1[1] = {
    {19, 2},
};
static arc arcs_6_2[1] = {
    {0, 2},
};
static state states_6[3] = {
    {1, arcs_6_0},
    {1, arcs_6_1},
    {1, arcs_6_2},
};
static arc arcs_7_0[1] = {
    {22, 1},
};
static arc arcs_7_1[1] = {
    {23, 2},
};
static arc arcs_7_2[1] = {
    {24, 3},
};
static arc arcs_7_3[2] = {
    {25, 4},
    {27, 5},
};
static arc arcs_7_4[1] = {
    {26, 6},
};
static arc arcs_7_5[1] = {
    {28, 7},
};
static arc arcs_7_6[1] = {
    {27, 5},
};
static arc arcs_7_7[1] = {
    {0, 7},
};
static state states_7[8] = {
    {1, arcs_7_0},
    {1, arcs_7_1},
    {1, arcs_7_2},
    {2, arcs_7_3},
    {1, arcs_7_4},
    {1, arcs_7_5},
    {1, arcs_7_6},
    {1, arcs_7_7},
};
static arc arcs_8_0[1] = {
    {13, 1},
};
static arc arcs_8_1[2] = {
    {29, 2},
    {15, 3},
};
static arc arcs_8_2[1] = {
    {15, 3},
};
static arc arcs_8_3[1] = {
    {0, 3},
};
static state states_8[4] = {
    {1, arcs_8_0},
    {2, arcs_8_1},
    {1, arcs_8_2},
    {1, arcs_8_3},
};
static arc arcs_9_0[3] = {
    {30, 1},
    {33, 2},
    {35, 3},
};
static arc arcs_9_1[3] = {
    {31, 4},
    {32, 5},
    {0, 1},
};
static arc arcs_9_2[3] = {
    {34, 6},
    {32, 7},
    {0, 2},
};
static arc arcs_9_3[1] = {
    {34, 8},
};
static arc arcs_9_4[1] = {
    {26, 9},
};
static arc arcs_9_5[4] = {
    {30, 1},
    {33, 2},
    {35, 3},
    {0, 5},
};
static arc arcs_9_6[2] = {
    {32, 7},
    {0, 6},
};
static arc arcs_9_7[2] = {
    {34, 10},
    {35, 3},
};
static arc arcs_9_8[1] = {
    {0, 8},
};
static arc arcs_9_9[2] = {
    {32, 5},
    {0, 9},
};
static arc arcs_9_10[3] = {
    {32, 7},
    {31, 11},
    {0, 10},
};
static arc arcs_9_11[1] = {
    {26, 6},
};
static state states_9[12] = {
    {3, arcs_9_0},
    {3, arcs_9_1},
    {3, arcs_9_2},
    {1, arcs_9_3},
    {1, arcs_9_4},
    {4, arcs_9_5},
    {2, arcs_9_6},
    {2, arcs_9_7},
    {1, arcs_9_8},
    {2, arcs_9_9},
    {3, arcs_9_10},
    {1, arcs_9_11},
};
static arc arcs_10_0[1] = {
    {23, 1},
};
static arc arcs_10_1[2] = {
    {27, 2},
    {0, 1},
};
static arc arcs_10_2[1] = {
    {26, 3},
};
static arc arcs_10_3[1] = {
    {0, 3},
};
static state states_10[4] = {
    {1, arcs_10_0},
    {2, arcs_10_1},
    {1, arcs_10_2},
    {1, arcs_10_3},
};
static arc arcs_11_0[2] = {
    {34, 1},
    {13, 2},
};
static arc arcs_11_1[1] = {
    {0, 1},
};
static arc arcs_11_2[1] = {
    {36, 3},
};
static arc arcs_11_3[1] = {
    {15, 1},
};
static state states_11[4] = {
    {2, arcs_11_0},
    {1, arcs_11_1},
    {1, arcs_11_2},
    {1, arcs_11_3},
};
static arc arcs_12_0[1] = {
    {30, 1},
};
static arc arcs_12_1[2] = {
    {32, 2},
    {0, 1},
};
static arc arcs_12_2[2] = {
    {30, 1},
    {0, 2},
};
static state states_12[3] = {
    {1, arcs_12_0},
    {2, arcs_12_1},
    {2, arcs_12_2},
};
static arc arcs_13_0[3] = {
    {38, 1},
    {33, 2},
    {35, 3},
};
static arc arcs_13_1[3] = {
    {31, 4},
    {32, 5},
    {0, 1},
};
static arc arcs_13_2[3] = {
    {39, 6},
    {32, 7},
    {0, 2},
};
static arc arcs_13_3[1] = {
    {39, 8},
};
static arc arcs_13_4[1] = {
    {26, 9},
};
static arc arcs_13_5[4] = {
    {38, 1},
    {33, 2},
    {35, 3},
    {0, 5},
};
static arc arcs_13_6[2] = {
    {32, 7},
    {0, 6},
};
static arc arcs_13_7[2] = {
    {39, 10},
    {35, 3},
};
static arc arcs_13_8[1] = {
    {0, 8},
};
static arc arcs_13_9[2] = {
    {32, 5},
    {0, 9},
};
static arc arcs_13_10[3] = {
    {32, 7},
    {31, 11},
    {0, 10},
};
static arc arcs_13_11[1] = {
    {26, 6},
};
static state states_13[12] = {
    {3, arcs_13_0},
    {3, arcs_13_1},
    {3, arcs_13_2},
    {1, arcs_13_3},
    {1, arcs_13_4},
    {4, arcs_13_5},
    {2, arcs_13_6},
    {2, arcs_13_7},
    {1, arcs_13_8},
    {2, arcs_13_9},
    {3, arcs_13_10},
    {1, arcs_13_11},
};
static arc arcs_14_0[1] = {
    {23, 1},
};
static arc arcs_14_1[1] = {
    {0, 1},
};
static state states_14[2] = {
    {1, arcs_14_0},
    {1, arcs_14_1},
};
static arc arcs_15_0[2] = {
    {39, 1},
    {13, 2},
};
static arc arcs_15_1[1] = {
    {0, 1},
};
static arc arcs_15_2[1] = {
    {40, 3},
};
static arc arcs_15_3[1] = {
    {15, 1},
};
static state states_15[4] = {
    {2, arcs_15_0},
    {1, arcs_15_1},
    {1, arcs_15_2},
    {1, arcs_15_3},
};
static arc arcs_16_0[1] = {
    {38, 1},
};
static arc arcs_16_1[2] = {
    {32, 2},
    {0, 1},
};
static arc arcs_16_2[2] = {
    {38, 1},
    {0, 2},
};
static state states_16[3] = {
    {1, arcs_16_0},
    {2, arcs_16_1},
    {2, arcs_16_2},
};
static arc arcs_17_0[2] = {
    {3, 1},
    {4, 1},
};
static arc arcs_17_1[1] = {
    {0, 1},
};
static state states_17[2] = {
    {2, arcs_17_0},
    {1, arcs_17_1},
};
static arc arcs_18_0[1] = {
    {41, 1},
};
static arc arcs_18_1[2] = {
    {42, 2},
    {2, 3},
};
static arc arcs_18_2[2] = {
    {41, 1},
    {2, 3},
};
static arc arcs_18_3[1] = {
    {0, 3},
};
static state states_18[4] = {
    {1, arcs_18_0},
    {2, arcs_18_1},
    {2, arcs_18_2},
    {1, arcs_18_3},
};
static arc arcs_19_0[9] = {
    {43, 1},
    {44, 1},
    {45, 1},
    {46, 1},
    {47, 1},
    {48, 1},
    {49, 1},
    {50, 1},
    {51, 1},
};
static arc arcs_19_1[1] = {
    {0, 1},
};
static state states_19[2] = {
    {9, arcs_19_0},
    {1, arcs_19_1},
};
static arc arcs_20_0[1] = {
    {9, 1},
};
static arc arcs_20_1[3] = {
    {52, 2},
    {31, 3},
    {0, 1},
};
static arc arcs_20_2[2] = {
    {53, 4},
    {9, 4},
};
static arc arcs_20_3[2] = {
    {53, 5},
    {9, 5},
};
static arc arcs_20_4[1] = {
    {0, 4},
};
static arc arcs_20_5[2] = {
    {31, 3},
    {0, 5},
};
static state states_20[6] = {
    {1, arcs_20_0},
    {3, arcs_20_1},
    {2, arcs_20_2},
    {2, arcs_20_3},
    {1, arcs_20_4},
    {2, arcs_20_5},
};
static arc arcs_21_0[13] = {
    {54, 1},
    {55, 1},
    {56, 1},
    {57, 1},
    {58, 1},
    {59, 1},
    {60, 1},
    {61, 1},
    {62, 1},
    {63, 1},
    {64, 1},
    {65, 1},
    {66, 1},
};
static arc arcs_21_1[1] = {
    {0, 1},
};
static state states_21[2] = {
    {13, arcs_21_0},
    {1, arcs_21_1},
};
static arc arcs_22_0[1] = {
    {67, 1},
};
static arc arcs_22_1[3] = {
    {26, 2},
    {68, 3},
    {0, 1},
};
static arc arcs_22_2[2] = {
    {32, 4},
    {0, 2},
};
static arc arcs_22_3[1] = {
    {26, 5},
};
static arc arcs_22_4[2] = {
    {26, 2},
    {0, 4},
};
static arc arcs_22_5[2] = {
    {32, 6},
    {0, 5},
};
static arc arcs_22_6[1] = {
    {26, 7},
};
static arc arcs_22_7[2] = {
    {32, 8},
    {0, 7},
};
static arc arcs_22_8[2] = {
    {26, 7},
    {0, 8},
};
static state states_22[9] = {
    {1, arcs_22_0},
    {3, arcs_22_1},
    {2, arcs_22_2},
    {1, arcs_22_3},
    {2, arcs_22_4},
    {2, arcs_22_5},
    {1, arcs_22_6},
    {2, arcs_22_7},
    {2, arcs_22_8},
};
static arc arcs_23_0[1] = {
    {69, 1},
};
static arc arcs_23_1[1] = {
    {70, 2},
};
static arc arcs_23_2[1] = {
    {0, 2},
};
static state states_23[3] = {
    {1, arcs_23_0},
    {1, arcs_23_1},
    {1, arcs_23_2},
};
static arc arcs_24_0[1] = {
    {71, 1},
};
static arc arcs_24_1[1] = {
    {0, 1},
};
static state states_24[2] = {
    {1, arcs_24_0},
    {1, arcs_24_1},
};
static arc arcs_25_0[5] = {
    {72, 1},
    {73, 1},
    {74, 1},
    {75, 1},
    {76, 1},
};
static arc arcs_25_1[1] = {
    {0, 1},
};
static state states_25[2] = {
    {5, arcs_25_0},
    {1, arcs_25_1},
};
static arc arcs_26_0[1] = {
    {77, 1},
};
static arc arcs_26_1[1] = {
    {0, 1},
};
static state states_26[2] = {
    {1, arcs_26_0},
    {1, arcs_26_1},
};
static arc arcs_27_0[1] = {
    {78, 1},
};
static arc arcs_27_1[1] = {
    {0, 1},
};
static state states_27[2] = {
    {1, arcs_27_0},
    {1, arcs_27_1},
};
static arc arcs_28_0[1] = {
    {79, 1},
};
static arc arcs_28_1[2] = {
    {9, 2},
    {0, 1},
};
static arc arcs_28_2[1] = {
    {0, 2},
};
static state states_28[3] = {
    {1, arcs_28_0},
    {2, arcs_28_1},
    {1, arcs_28_2},
};
static arc arcs_29_0[1] = {
    {53, 1},
};
static arc arcs_29_1[1] = {
    {0, 1},
};
static state states_29[2] = {
    {1, arcs_29_0},
    {1, arcs_29_1},
};
static arc arcs_30_0[1] = {
    {80, 1},
};
static arc arcs_30_1[2] = {
    {26, 2},
    {0, 1},
};
static arc arcs_30_2[2] = {
    {32, 3},
    {0, 2},
};
static arc arcs_30_3[1] = {
    {26, 4},
};
static arc arcs_30_4[2] = {
    {32, 5},
    {0, 4},
};
static arc arcs_30_5[1] = {
    {26, 6},
};
static arc arcs_30_6[1] = {
    {0, 6},
};
static state states_30[7] = {
    {1, arcs_30_0},
    {2, arcs_30_1},
    {2, arcs_30_2},
    {1, arcs_30_3},
    {2, arcs_30_4},
    {1, arcs_30_5},
    {1, arcs_30_6},
};
static arc arcs_31_0[2] = {
    {81, 1},
    {82, 1},
};
static arc arcs_31_1[1] = {
    {0, 1},
};
static state states_31[2] = {
    {2, arcs_31_0},
    {1, arcs_31_1},
};
static arc arcs_32_0[1] = {
    {83, 1},
};
static arc arcs_32_1[1] = {
    {84, 2},
};
static arc arcs_32_2[1] = {
    {0, 2},
};
static state states_32[3] = {
    {1, arcs_32_0},
    {1, arcs_32_1},
    {1, arcs_32_2},
};
static arc arcs_33_0[1] = {
    {85, 1},
};
static arc arcs_33_1[2] = {
    {86, 2},
    {12, 3},
};
static arc arcs_33_2[3] = {
    {86, 2},
    {12, 3},
    {83, 4},
};
static arc arcs_33_3[1] = {
    {83, 4},
};
static arc arcs_33_4[3] = {
    {33, 5},
    {13, 6},
    {87, 5},
};
static arc arcs_33_5[1] = {
    {0, 5},
};
static arc arcs_33_6[1] = {
    {87, 7},
};
static arc arcs_33_7[1] = {
    {15, 5},
};
static state states_33[8] = {
    {1, arcs_33_0},
    {2, arcs_33_1},
    {3, arcs_33_2},
    {1, arcs_33_3},
    {3, arcs_33_4},
    {1, arcs_33_5},
    {1, arcs_33_6},
    {1, arcs_33_7},
};
static arc arcs_34_0[1] = {
    {23, 1},
};
static arc arcs_34_1[2] = {
    {89, 2},
    {0, 1},
};
static arc arcs_34_2[1] = {
    {23, 3},
};
static arc arcs_34_3[1] = {
    {0, 3},
};
static state states_34[4] = {
    {1, arcs_34_0},
    {2, arcs_34_1},
    {1, arcs_34_2},
    {1, arcs_34_3},
};
static arc arcs_35_0[1] = {
    {12, 1},
};
static arc arcs_35_1[2] = {
    {89, 2},
    {0, 1},
};
static arc arcs_35_2[1] = {
    {23, 3},
};
static arc arcs_35_3[1] = {
    {0, 3},
};
static state states_35[4] = {
    {1, arcs_35_0},
    {2, arcs_35_1},
    {1, arcs_35_2},
    {1, arcs_35_3},
};
static arc arcs_36_0[1] = {
    {88, 1},
};
static arc arcs_36_1[2] = {
    {32, 2},
    {0, 1},
};
static arc arcs_36_2[2] = {
    {88, 1},
    {0, 2},
};
static state states_36[3] = {
    {1, arcs_36_0},
    {2, arcs_36_1},
    {2, arcs_36_2},
};
static arc arcs_37_0[1] = {
    {90, 1},
};
static arc arcs_37_1[2] = {
    {32, 0},
    {0, 1},
};
static state states_37[2] = {
    {1, arcs_37_0},
    {2, arcs_37_1},
};
static arc arcs_38_0[1] = {
    {23, 1},
};
static arc arcs_38_1[2] = {
    {86, 0},
    {0, 1},
};
static state states_38[2] = {
    {1, arcs_38_0},
    {2, arcs_38_1},
};
static arc arcs_39_0[1] = {
    {91, 1},
};
static arc arcs_39_1[1] = {
    {23, 2},
};
static arc arcs_39_2[2] = {
    {32, 1},
    {0, 2},
};
static state states_39[3] = {
    {1, arcs_39_0},
    {1, arcs_39_1},
    {2, arcs_39_2},
};
static arc arcs_40_0[1] = {
    {92, 1},
};
static arc arcs_40_1[1] = {
    {93, 2},
};
static arc arcs_40_2[2] = {
    {94, 3},
    {0, 2},
};
static arc arcs_40_3[1] = {
    {26, 4},
};
static arc arcs_40_4[2] = {
    {32, 5},
    {0, 4},
};
static arc arcs_40_5[1] = {
    {26, 6},
};
static arc arcs_40_6[1] = {
    {0, 6},
};
static state states_40[7] = {
    {1, arcs_40_0},
    {1, arcs_40_1},
    {2, arcs_40_2},
    {1, arcs_40_3},
    {2, arcs_40_4},
    {1, arcs_40_5},
    {1, arcs_40_6},
};
static arc arcs_41_0[1] = {
    {95, 1},
};
static arc arcs_41_1[1] = {
    {26, 2},
};
static arc arcs_41_2[2] = {
    {32, 3},
    {0, 2},
};
static arc arcs_41_3[1] = {
    {26, 4},
};
static arc arcs_41_4[1] = {
    {0, 4},
};
static state states_41[5] = {
    {1, arcs_41_0},
    {1, arcs_41_1},
    {2, arcs_41_2},
    {1, arcs_41_3},
    {1, arcs_41_4},
};
static arc arcs_42_0[9] = {
    {96, 1},
    {97, 1},
    {98, 1},
    {99, 1},
    {100, 1},
    {19, 1},
    {18, 1},
    {17, 1},
    {101, 1},
};
static arc arcs_42_1[1] = {
    {0, 1},
};
static state states_42[2] = {
    {9, arcs_42_0},
    {1, arcs_42_1},
};
static arc arcs_43_0[1] = {
    {21, 1},
};
static arc arcs_43_1[3] = {
    {19, 2},
    {100, 2},
    {98, 2},
};
static arc arcs_43_2[1] = {
    {0, 2},
};
static state states_43[3] = {
    {1, arcs_43_0},
    {3, arcs_43_1},
    {1, arcs_43_2},
};
static arc arcs_44_0[1] = {
    {102, 1},
};
static arc arcs_44_1[1] = {
    {26, 2},
};
static arc arcs_44_2[1] = {
    {27, 3},
};
static arc arcs_44_3[1] = {
    {28, 4},
};
static arc arcs_44_4[3] = {
    {103, 1},
    {104, 5},
    {0, 4},
};
static arc arcs_44_5[1] = {
    {27, 6},
};
static arc arcs_44_6[1] = {
    {28, 7},
};
static arc arcs_44_7[1] = {
    {0, 7},
};
static state states_44[8] = {
    {1, arcs_44_0},
    {1, arcs_44_1},
    {1, arcs_44_2},
    {1, arcs_44_3},
    {3, arcs_44_4},
    {1, arcs_44_5},
    {1, arcs_44_6},
    {1, arcs_44_7},
};
static arc arcs_45_0[1] = {
    {105, 1},
};
static arc arcs_45_1[1] = {
    {26, 2},
};
static arc arcs_45_2[1] = {
    {27, 3},
};
static arc arcs_45_3[1] = {
    {28, 4},
};
static arc arcs_45_4[2] = {
    {104, 5},
    {0, 4},
};
static arc arcs_45_5[1] = {
    {27, 6},
};
static arc arcs_45_6[1] = {
    {28, 7},
};
static arc arcs_45_7[1] = {
    {0, 7},
};
static state states_45[8] = {
    {1, arcs_45_0},
    {1, arcs_45_1},
    {1, arcs_45_2},
    {1, arcs_45_3},
    {2, arcs_45_4},
    {1, arcs_45_5},
    {1, arcs_45_6},
    {1, arcs_45_7},
};
static arc arcs_46_0[1] = {
    {106, 1},
};
static arc arcs_46_1[1] = {
    {70, 2},
};
static arc arcs_46_2[1] = {
    {94, 3},
};
static arc arcs_46_3[1] = {
    {9, 4},
};
static arc arcs_46_4[1] = {
    {27, 5},
};
static arc arcs_46_5[1] = {
    {28, 6},
};
static arc arcs_46_6[2] = {
    {104, 7},
    {0, 6},
};
static arc arcs_46_7[1] = {
    {27, 8},
};
static arc arcs_46_8[1] = {
    {28, 9},
};
static arc arcs_46_9[1] = {
    {0, 9},
};
static state states_46[10] = {
    {1, arcs_46_0},
    {1, arcs_46_1},
    {1, arcs_46_2},
    {1, arcs_46_3},
    {1, arcs_46_4},
    {1, arcs_46_5},
    {2, arcs_46_6},
    {1, arcs_46_7},
    {1, arcs_46_8},
    {1, arcs_46_9},
};
static arc arcs_47_0[1] = {
    {107, 1},
};
static arc arcs_47_1[1] = {
    {27, 2},
};
static arc arcs_47_2[1] = {
    {28, 3},
};
static arc arcs_47_3[2] = {
    {108, 4},
    {109, 5},
};
static arc arcs_47_4[1] = {
    {27, 6},
};
static arc arcs_47_5[1] = {
    {27, 7},
};
static arc arcs_47_6[1] = {
    {28, 8},
};
static arc arcs_47_7[1] = {
    {28, 9},
};
static arc arcs_47_8[4] = {
    {108, 4},
    {104, 10},
    {109, 5},
    {0, 8},
};
static arc arcs_47_9[1] = {
    {0, 9},
};
static arc arcs_47_10[1] = {
    {27, 11},
};
static arc arcs_47_11[1] = {
    {28, 12},
};
static arc arcs_47_12[2] = {
    {109, 5},
    {0, 12},
};
static state states_47[13] = {
    {1, arcs_47_0},
    {1, arcs_47_1},
    {1, arcs_47_2},
    {2, arcs_47_3},
    {1, arcs_47_4},
    {1, arcs_47_5},
    {1, arcs_47_6},
    {1, arcs_47_7},
    {4, arcs_47_8},
    {1, arcs_47_9},
    {1, arcs_47_10},
    {1, arcs_47_11},
    {2, arcs_47_12},
};
static arc arcs_48_0[1] = {
    {110, 1},
};
static arc arcs_48_1[1] = {
    {111, 2},
};
static arc arcs_48_2[2] = {
    {32, 1},
    {27, 3},
};
static arc arcs_48_3[1] = {
    {28, 4},
};
static arc arcs_48_4[1] = {
    {0, 4},
};
static state states_48[5] = {
    {1, arcs_48_0},
    {1, arcs_48_1},
    {2, arcs_48_2},
    {1, arcs_48_3},
    {1, arcs_48_4},
};
static arc arcs_49_0[1] = {
    {26, 1},
};
static arc arcs_49_1[2] = {
    {89, 2},
    {0, 1},
};
static arc arcs_49_2[1] = {
    {93, 3},
};
static arc arcs_49_3[1] = {
    {0, 3},
};
static state states_49[4] = {
    {1, arcs_49_0},
    {2, arcs_49_1},
    {1, arcs_49_2},
    {1, arcs_49_3},
};
static arc arcs_50_0[1] = {
    {112, 1},
};
static arc arcs_50_1[2] = {
    {26, 2},
    {0, 1},
};
static arc arcs_50_2[3] = {
    {89, 3},
    {32, 3},
    {0, 2},
};
static arc arcs_50_3[1] = {
    {26, 4},
};
static arc arcs_50_4[1] = {
    {0, 4},
};
static state states_50[5] = {
    {1, arcs_50_0},
    {2, arcs_50_1},
    {3, arcs_50_2},
    {1, arcs_50_3},
    {1, arcs_50_4},
};
static arc arcs_51_0[2] = {
    {3, 1},
    {2, 2},
};
static arc arcs_51_1[1] = {
    {0, 1},
};
static arc arcs_51_2[1] = {
    {113, 3},
};
static arc arcs_51_3[1] = {
    {6, 4},
};
static arc arcs_51_4[2] = {
    {6, 4},
    {114, 1},
};
static state states_51[5] = {
    {2, arcs_51_0},
    {1, arcs_51_1},
    {1, arcs_51_2},
    {1, arcs_51_3},
    {2, arcs_51_4},
};
static arc arcs_52_0[1] = {
    {116, 1},
};
static arc arcs_52_1[2] = {
    {32, 2},
    {0, 1},
};
static arc arcs_52_2[1] = {
    {116, 3},
};
static arc arcs_52_3[2] = {
    {32, 4},
    {0, 3},
};
static arc arcs_52_4[2] = {
    {116, 3},
    {0, 4},
};
static state states_52[5] = {
    {1, arcs_52_0},
    {2, arcs_52_1},
    {1, arcs_52_2},
    {2, arcs_52_3},
    {2, arcs_52_4},
};
static arc arcs_53_0[2] = {
    {117, 1},
    {118, 1},
};
static arc arcs_53_1[1] = {
    {0, 1},
};
static state states_53[2] = {
    {2, arcs_53_0},
    {1, arcs_53_1},
};
static arc arcs_54_0[1] = {
    {119, 1},
};
static arc arcs_54_1[2] = {
    {37, 2},
    {27, 3},
};
static arc arcs_54_2[1] = {
    {27, 3},
};
static arc arcs_54_3[1] = {
    {116, 4},
};
static arc arcs_54_4[1] = {
    {0, 4},
};
static state states_54[5] = {
    {1, arcs_54_0},
    {2, arcs_54_1},
    {1, arcs_54_2},
    {1, arcs_54_3},
    {1, arcs_54_4},
};
static arc arcs_55_0[2] = {
    {117, 1},
    {120, 2},
};
static arc arcs_55_1[2] = {
    {102, 3},
    {0, 1},
};
static arc arcs_55_2[1] = {
    {0, 2},
};
static arc arcs_55_3[1] = {
    {117, 4},
};
static arc arcs_55_4[1] = {
    {104, 5},
};
static arc arcs_55_5[1] = {
    {26, 2},
};
static state states_55[6] = {
    {2, arcs_55_0},
    {2, arcs_55_1},
    {1, arcs_55_2},
    {1, arcs_55_3},
    {1, arcs_55_4},
    {1, arcs_55_5},
};
static arc arcs_56_0[1] = {
    {121, 1},
};
static arc arcs_56_1[2] = {
    {122, 0},
    {0, 1},
};
static state states_56[2] = {
    {1, arcs_56_0},
    {2, arcs_56_1},
};
static arc arcs_57_0[1] = {
    {123, 1},
};
static arc arcs_57_1[2] = {
    {124, 0},
    {0, 1},
};
static state states_57[2] = {
    {1, arcs_57_0},
    {2, arcs_57_1},
};
static arc arcs_58_0[2] = {
    {125, 1},
    {126, 2},
};
static arc arcs_58_1[1] = {
    {123, 2},
};
static arc arcs_58_2[1] = {
    {0, 2},
};
static state states_58[3] = {
    {2, arcs_58_0},
    {1, arcs_58_1},
    {1, arcs_58_2},
};
static arc arcs_59_0[1] = {
    {93, 1},
};
static arc arcs_59_1[2] = {
    {127, 0},
    {0, 1},
};
static state states_59[2] = {
    {1, arcs_59_0},
    {2, arcs_59_1},
};
static arc arcs_60_0[10] = {
    {128, 1},
    {129, 1},
    {130, 1},
    {131, 1},
    {132, 1},
    {133, 1},
    {134, 1},
    {94, 1},
    {125, 2},
    {135, 3},
};
static arc arcs_60_1[1] = {
    {0, 1},
};
static arc arcs_60_2[1] = {
    {94, 1},
};
static arc arcs_60_3[2] = {
    {125, 1},
    {0, 3},
};
static state states_60[4] = {
    {10, arcs_60_0},
    {1, arcs_60_1},
    {1, arcs_60_2},
    {2, arcs_60_3},
};
static arc arcs_61_0[1] = {
    {136, 1},
};
static arc arcs_61_1[2] = {
    {137, 0},
    {0, 1},
};
static state states_61[2] = {
    {1, arcs_61_0},
    {2, arcs_61_1},
};
static arc arcs_62_0[1] = {
    {138, 1},
};
static arc arcs_62_1[2] = {
    {139, 0},
    {0, 1},
};
static state states_62[2] = {
    {1, arcs_62_0},
    {2, arcs_62_1},
};
static arc arcs_63_0[1] = {
    {140, 1},
};
static arc arcs_63_1[2] = {
    {141, 0},
    {0, 1},
};
static state states_63[2] = {
    {1, arcs_63_0},
    {2, arcs_63_1},
};
static arc arcs_64_0[1] = {
    {142, 1},
};
static arc arcs_64_1[3] = {
    {143, 0},
    {68, 0},
    {0, 1},
};
static state states_64[2] = {
    {1, arcs_64_0},
    {3, arcs_64_1},
};
static arc arcs_65_0[1] = {
    {144, 1},
};
static arc arcs_65_1[3] = {
    {145, 0},
    {146, 0},
    {0, 1},
};
static state states_65[2] = {
    {1, arcs_65_0},
    {3, arcs_65_1},
};
static arc arcs_66_0[1] = {
    {147, 1},
};
static arc arcs_66_1[6] = {
    {33, 0},
    {11, 0},
    {148, 0},
    {149, 0},
    {150, 0},
    {0, 1},
};
static state states_66[2] = {
    {1, arcs_66_0},
    {6, arcs_66_1},
};
static arc arcs_67_0[4] = {
    {145, 1},
    {146, 1},
    {151, 1},
    {152, 2},
};
static arc arcs_67_1[1] = {
    {147, 2},
};
static arc arcs_67_2[1] = {
    {0, 2},
};
static state states_67[3] = {
    {4, arcs_67_0},
    {1, arcs_67_1},
    {1, arcs_67_2},
};
static arc arcs_68_0[1] = {
    {153, 1},
};
static arc arcs_68_1[2] = {
    {35, 2},
    {0, 1},
};
static arc arcs_68_2[1] = {
    {147, 3},
};
static arc arcs_68_3[1] = {
    {0, 3},
};
static state states_68[4] = {
    {1, arcs_68_0},
    {2, arcs_68_1},
    {1, arcs_68_2},
    {1, arcs_68_3},
};
static arc arcs_69_0[2] = {
    {154, 1},
    {155, 2},
};
static arc arcs_69_1[1] = {
    {155, 2},
};
static arc arcs_69_2[2] = {
    {156, 2},
    {0, 2},
};
static state states_69[3] = {
    {2, arcs_69_0},
    {1, arcs_69_1},
    {2, arcs_69_2},
};
static arc arcs_70_0[7] = {
    {13, 1},
    {158, 2},
    {161, 3},
    {164, 4},
    {23, 5},
    {166, 5},
    {167, 6},
};
static arc arcs_70_1[3] = {
    {53, 7},
    {157, 7},
    {15, 5},
};
static arc arcs_70_2[2] = {
    {159, 8},
    {160, 5},
};
static arc arcs_70_3[2] = {
    {162, 9},
    {163, 5},
};
static arc arcs_70_4[1] = {
    {165, 10},
};
static arc arcs_70_5[1] = {
    {0, 5},
};
static arc arcs_70_6[2] = {
    {167, 6},
    {0, 6},
};
static arc arcs_70_7[1] = {
    {15, 5},
};
static arc arcs_70_8[1] = {
    {160, 5},
};
static arc arcs_70_9[1] = {
    {163, 5},
};
static arc arcs_70_10[1] = {
    {164, 5},
};
static state states_70[11] = {
    {7, arcs_70_0},
    {3, arcs_70_1},
    {2, arcs_70_2},
    {2, arcs_70_3},
    {1, arcs_70_4},
    {1, arcs_70_5},
    {2, arcs_70_6},
    {1, arcs_70_7},
    {1, arcs_70_8},
    {1, arcs_70_9},
    {1, arcs_70_10},
};
static arc arcs_71_0[1] = {
    {26, 1},
};
static arc arcs_71_1[3] = {
    {168, 2},
    {32, 3},
    {0, 1},
};
static arc arcs_71_2[1] = {
    {0, 2},
};
static arc arcs_71_3[2] = {
    {26, 4},
    {0, 3},
};
static arc arcs_71_4[2] = {
    {32, 3},
    {0, 4},
};
static state states_71[5] = {
    {1, arcs_71_0},
    {3, arcs_71_1},
    {1, arcs_71_2},
    {2, arcs_71_3},
    {2, arcs_71_4},
};
static arc arcs_72_0[1] = {
    {26, 1},
};
static arc arcs_72_1[3] = {
    {169, 2},
    {32, 3},
    {0, 1},
};
static arc arcs_72_2[1] = {
    {0, 2},
};
static arc arcs_72_3[2] = {
    {26, 4},
    {0, 3},
};
static arc arcs_72_4[2] = {
    {32, 3},
    {0, 4},
};
static state states_72[5] = {
    {1, arcs_72_0},
    {3, arcs_72_1},
    {1, arcs_72_2},
    {2, arcs_72_3},
    {2, arcs_72_4},
};
static arc arcs_73_0[1] = {
    {119, 1},
};
static arc arcs_73_1[2] = {
    {37, 2},
    {27, 3},
};
static arc arcs_73_2[1] = {
    {27, 3},
};
static arc arcs_73_3[1] = {
    {26, 4},
};
static arc arcs_73_4[1] = {
    {0, 4},
};
static state states_73[5] = {
    {1, arcs_73_0},
    {2, arcs_73_1},
    {1, arcs_73_2},
    {1, arcs_73_3},
    {1, arcs_73_4},
};
static arc arcs_74_0[3] = {
    {13, 1},
    {158, 2},
    {86, 3},
};
static arc arcs_74_1[2] = {
    {14, 4},
    {15, 5},
};
static arc arcs_74_2[1] = {
    {170, 6},
};
static arc arcs_74_3[1] = {
    {23, 5},
};
static arc arcs_74_4[1] = {
    {15, 5},
};
static arc arcs_74_5[1] = {
    {0, 5},
};
static arc arcs_74_6[1] = {
    {160, 5},
};
static state states_74[7] = {
    {3, arcs_74_0},
    {2, arcs_74_1},
    {1, arcs_74_2},
    {1, arcs_74_3},
    {1, arcs_74_4},
    {1, arcs_74_5},
    {1, arcs_74_6},
};
static arc arcs_75_0[1] = {
    {171, 1},
};
static arc arcs_75_1[2] = {
    {32, 2},
    {0, 1},
};
static arc arcs_75_2[2] = {
    {171, 1},
    {0, 2},
};
static state states_75[3] = {
    {1, arcs_75_0},
    {2, arcs_75_1},
    {2, arcs_75_2},
};
static arc arcs_76_0[3] = {
    {86, 1},
    {26, 2},
    {27, 3},
};
static arc arcs_76_1[1] = {
    {86, 4},
};
static arc arcs_76_2[2] = {
    {27, 3},
    {0, 2},
};
static arc arcs_76_3[3] = {
    {26, 5},
    {172, 6},
    {0, 3},
};
static arc arcs_76_4[1] = {
    {86, 6},
};
static arc arcs_76_5[2] = {
    {172, 6},
    {0, 5},
};
static arc arcs_76_6[1] = {
    {0, 6},
};
static state states_76[7] = {
    {3, arcs_76_0},
    {1, arcs_76_1},
    {2, arcs_76_2},
    {3, arcs_76_3},
    {1, arcs_76_4},
    {2, arcs_76_5},
    {1, arcs_76_6},
};
static arc arcs_77_0[1] = {
    {27, 1},
};
static arc arcs_77_1[2] = {
    {26, 2},
    {0, 1},
};
static arc arcs_77_2[1] = {
    {0, 2},
};
static state states_77[3] = {
    {1, arcs_77_0},
    {2, arcs_77_1},
    {1, arcs_77_2},
};
static arc arcs_78_0[1] = {
    {93, 1},
};
static arc arcs_78_1[2] = {
    {32, 2},
    {0, 1},
};
static arc arcs_78_2[2] = {
    {93, 1},
    {0, 2},
};
static state states_78[3] = {
    {1, arcs_78_0},
    {2, arcs_78_1},
    {2, arcs_78_2},
};
static arc arcs_79_0[1] = {
    {26, 1},
};
static arc arcs_79_1[2] = {
    {32, 2},
    {0, 1},
};
static arc arcs_79_2[2] = {
    {26, 1},
    {0, 2},
};
static state states_79[3] = {
    {1, arcs_79_0},
    {2, arcs_79_1},
    {2, arcs_79_2},
};
static arc arcs_80_0[1] = {
    {26, 1},
};
static arc arcs_80_1[4] = {
    {27, 2},
    {169, 3},
    {32, 4},
    {0, 1},
};
static arc arcs_80_2[1] = {
    {26, 5},
};
static arc arcs_80_3[1] = {
    {0, 3},
};
static arc arcs_80_4[2] = {
    {26, 6},
    {0, 4},
};
static arc arcs_80_5[3] = {
    {169, 3},
    {32, 7},
    {0, 5},
};
static arc arcs_80_6[2] = {
    {32, 4},
    {0, 6},
};
static arc arcs_80_7[2] = {
    {26, 8},
    {0, 7},
};
static arc arcs_80_8[1] = {
    {27, 9},
};
static arc arcs_80_9[1] = {
    {26, 10},
};
static arc arcs_80_10[2] = {
    {32, 7},
    {0, 10},
};
static state states_80[11] = {
    {1, arcs_80_0},
    {4, arcs_80_1},
    {1, arcs_80_2},
    {1, arcs_80_3},
    {2, arcs_80_4},
    {3, arcs_80_5},
    {2, arcs_80_6},
    {2, arcs_80_7},
    {1, arcs_80_8},
    {1, arcs_80_9},
    {2, arcs_80_10},
};
static arc arcs_81_0[1] = {
    {173, 1},
};
static arc arcs_81_1[1] = {
    {23, 2},
};
static arc arcs_81_2[2] = {
    {13, 3},
    {27, 4},
};
static arc arcs_81_3[2] = {
    {9, 5},
    {15, 6},
};
static arc arcs_81_4[1] = {
    {28, 7},
};
static arc arcs_81_5[1] = {
    {15, 6},
};
static arc arcs_81_6[1] = {
    {27, 4},
};
static arc arcs_81_7[1] = {
    {0, 7},
};
static state states_81[8] = {
    {1, arcs_81_0},
    {1, arcs_81_1},
    {2, arcs_81_2},
    {2, arcs_81_3},
    {1, arcs_81_4},
    {1, arcs_81_5},
    {1, arcs_81_6},
    {1, arcs_81_7},
};
static arc arcs_82_0[3] = {
    {174, 1},
    {33, 2},
    {35, 3},
};
static arc arcs_82_1[2] = {
    {32, 4},
    {0, 1},
};
static arc arcs_82_2[1] = {
    {26, 5},
};
static arc arcs_82_3[1] = {
    {26, 6},
};
static arc arcs_82_4[4] = {
    {174, 1},
    {33, 2},
    {35, 3},
    {0, 4},
};
static arc arcs_82_5[2] = {
    {32, 7},
    {0, 5},
};
static arc arcs_82_6[1] = {
    {0, 6},
};
static arc arcs_82_7[2] = {
    {174, 5},
    {35, 3},
};
static state states_82[8] = {
    {3, arcs_82_0},
    {2, arcs_82_1},
    {1, arcs_82_2},
    {1, arcs_82_3},
    {4, arcs_82_4},
    {2, arcs_82_5},
    {1, arcs_82_6},
    {2, arcs_82_7},
};
static arc arcs_83_0[1] = {
    {26, 1},
};
static arc arcs_83_1[3] = {
    {169, 2},
    {31, 3},
    {0, 1},
};
static arc arcs_83_2[1] = {
    {0, 2},
};
static arc arcs_83_3[1] = {
    {26, 2},
};
static state states_83[4] = {
    {1, arcs_83_0},
    {3, arcs_83_1},
    {1, arcs_83_2},
    {1, arcs_83_3},
};
static arc arcs_84_0[2] = {
    {168, 1},
    {176, 1},
};
static arc arcs_84_1[1] = {
    {0, 1},
};
static state states_84[2] = {
    {2, arcs_84_0},
    {1, arcs_84_1},
};
static arc arcs_85_0[1] = {
    {106, 1},
};
static arc arcs_85_1[1] = {
    {70, 2},
};
static arc arcs_85_2[1] = {
    {94, 3},
};
static arc arcs_85_3[1] = {
    {115, 4},
};
static arc arcs_85_4[2] = {
    {175, 5},
    {0, 4},
};
static arc arcs_85_5[1] = {
    {0, 5},
};
static state states_85[6] = {
    {1, arcs_85_0},
    {1, arcs_85_1},
    {1, arcs_85_2},
    {1, arcs_85_3},
    {2, arcs_85_4},
    {1, arcs_85_5},
};
static arc arcs_86_0[1] = {
    {102, 1},
};
static arc arcs_86_1[1] = {
    {116, 2},
};
static arc arcs_86_2[2] = {
    {175, 3},
    {0, 2},
};
static arc arcs_86_3[1] = {
    {0, 3},
};
static state states_86[4] = {
    {1, arcs_86_0},
    {1, arcs_86_1},
    {2, arcs_86_2},
    {1, arcs_86_3},
};
static arc arcs_87_0[2] = {
    {169, 1},
    {178, 1},
};
static arc arcs_87_1[1] = {
    {0, 1},
};
static state states_87[2] = {
    {2, arcs_87_0},
    {1, arcs_87_1},
};
static arc arcs_88_0[1] = {
    {106, 1},
};
static arc arcs_88_1[1] = {
    {70, 2},
};
static arc arcs_88_2[1] = {
    {94, 3},
};
static arc arcs_88_3[1] = {
    {117, 4},
};
static arc arcs_88_4[2] = {
    {177, 5},
    {0, 4},
};
static arc arcs_88_5[1] = {
    {0, 5},
};
static state states_88[6] = {
    {1, arcs_88_0},
    {1, arcs_88_1},
    {1, arcs_88_2},
    {1, arcs_88_3},
    {2, arcs_88_4},
    {1, arcs_88_5},
};
static arc arcs_89_0[1] = {
    {102, 1},
};
static arc arcs_89_1[1] = {
    {116, 2},
};
static arc arcs_89_2[2] = {
    {177, 3},
    {0, 2},
};
static arc arcs_89_3[1] = {
    {0, 3},
};
static state states_89[4] = {
    {1, arcs_89_0},
    {1, arcs_89_1},
    {2, arcs_89_2},
    {1, arcs_89_3},
};
static arc arcs_90_0[1] = {
    {26, 1},
};
static arc arcs_90_1[2] = {
    {32, 0},
    {0, 1},
};
static state states_90[2] = {
    {1, arcs_90_0},
    {2, arcs_90_1},
};
static arc arcs_91_0[1] = {
    {23, 1},
};
static arc arcs_91_1[1] = {
    {0, 1},
};
static state states_91[2] = {
    {1, arcs_91_0},
    {1, arcs_91_1},
};
static arc arcs_92_0[1] = {
    {180, 1},
};
static arc arcs_92_1[2] = {
    {181, 2},
    {0, 1},
};
static arc arcs_92_2[1] = {
    {0, 2},
};
static state states_92[3] = {
    {1, arcs_92_0},
    {2, arcs_92_1},
    {1, arcs_92_2},
};
static arc arcs_93_0[2] = {
    {85, 1},
    {9, 2},
};
static arc arcs_93_1[1] = {
    {26, 2},
};
static arc arcs_93_2[1] = {
    {0, 2},
};
static state states_93[3] = {
    {2, arcs_93_0},
    {1, arcs_93_1},
    {1, arcs_93_2},
};
static dfa dfas[94] = {
    {256, "single_input", 0, 3, states_0,
     "\004\050\340\000\000\000\000\000\250\340\051\230\100\116\200\040\000\000\206\104\322\040\020"},
    {257, "file_input", 0, 2, states_1,
     "\204\050\340\000\000\000\000\000\250\340\051\230\100\116\200\040\000\000\206\104\322\040\020"},
    {258, "eval_input", 0, 3, states_2,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\200\040\000\000\206\104\322\000\000"},
    {259, "decorator", 0, 7, states_3,
     "\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {260, "decorators", 0, 2, states_4,
     "\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {261, "decorated", 0, 3, states_5,
     "\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {262, "async_funcdef", 0, 3, states_6,
     "\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {263, "funcdef", 0, 8, states_7,
     "\000\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {264, "parameters", 0, 4, states_8,
     "\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {265, "typedargslist", 0, 12, states_9,
     "\000\040\200\000\012\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {266, "tname", 0, 4, states_10,
     "\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {267, "tfpdef", 0, 4, states_11,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {268, "tfplist", 0, 3, states_12,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {269, "varargslist", 0, 12, states_13,
     "\000\040\200\000\012\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {270, "vname", 0, 2, states_14,
     "\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {271, "vfpdef", 0, 4, states_15,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {272, "vfplist", 0, 3, states_16,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {273, "stmt", 0, 2, states_17,
     "\000\050\340\000\000\000\000\000\250\340\051\230\100\116\200\040\000\000\206\104\322\040\020"},
    {274, "simple_stmt", 0, 4, states_18,
     "\000\040\200\000\000\000\000\000\250\340\051\230\000\000\200\040\000\000\206\104\322\000\020"},
    {275, "small_stmt", 0, 2, states_19,
     "\000\040\200\000\000\000\000\000\250\340\051\230\000\000\200\040\000\000\206\104\322\000\020"},
    {276, "expr_stmt", 0, 6, states_20,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\200\040\000\000\206\104\322\000\000"},
    {277, "augassign", 0, 2, states_21,
     "\000\000\000\000\000\000\300\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {278, "print_stmt", 0, 9, states_22,
     "\000\000\000\000\000\000\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {279, "del_stmt", 0, 3, states_23,
     "\000\000\000\000\000\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {280, "pass_stmt", 0, 2, states_24,
     "\000\000\000\000\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {281, "flow_stmt", 0, 2, states_25,
     "\000\000\000\000\000\000\000\000\000\340\001\000\000\000\000\000\000\000\000\000\000\000\020"},
    {282, "break_stmt", 0, 2, states_26,
     "\000\000\000\000\000\000\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {283, "continue_stmt", 0, 2, states_27,
     "\000\000\000\000\000\000\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {284, "return_stmt", 0, 3, states_28,
     "\000\000\000\000\000\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {285, "yield_stmt", 0, 2, states_29,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\020"},
    {286, "raise_stmt", 0, 7, states_30,
     "\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000"},
    {287, "import_stmt", 0, 2, states_31,
     "\000\000\000\000\000\000\000\000\000\000\050\000\000\000\000\000\000\000\000\000\000\000\000"},
    {288, "import_name", 0, 3, states_32,
     "\000\000\000\000\000\000\000\000\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000"},
    {289, "import_from", 0, 8, states_33,
     "\000\000\000\000\000\000\000\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000"},
    {290, "import_as_name", 0, 4, states_34,
     "\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {291, "dotted_as_name", 0, 4, states_35,
     "\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {292, "import_as_names", 0, 3, states_36,
     "\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {293, "dotted_as_names", 0, 2, states_37,
     "\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {294, "dotted_name", 0, 2, states_38,
     "\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {295, "global_stmt", 0, 3, states_39,
     "\000\000\000\000\000\000\000\000\000\000\000\010\000\000\000\000\000\000\000\000\000\000\000"},
    {296, "exec_stmt", 0, 7, states_40,
     "\000\000\000\000\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000"},
    {297, "assert_stmt", 0, 5, states_41,
     "\000\000\000\000\000\000\000\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000"},
    {298, "compound_stmt", 0, 2, states_42,
     "\000\010\140\000\000\000\000\000\000\000\000\000\100\116\000\000\000\000\000\000\000\040\000"},
    {299, "async_stmt", 0, 3, states_43,
     "\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {300, "if_stmt", 0, 8, states_44,
     "\000\000\000\000\000\000\000\000\000\000\000\000\100\000\000\000\000\000\000\000\000\000\000"},
    {301, "while_stmt", 0, 8, states_45,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\000\000"},
    {302, "for_stmt", 0, 10, states_46,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\000"},
    {303, "try_stmt", 0, 13, states_47,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\010\000\000\000\000\000\000\000\000\000"},
    {304, "with_stmt", 0, 5, states_48,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\100\000\000\000\000\000\000\000\000\000"},
    {305, "with_item", 0, 4, states_49,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\200\040\000\000\206\104\322\000\000"},
    {306, "except_clause", 0, 5, states_50,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\000"},
    {307, "suite", 0, 5, states_51,
     "\004\040\200\000\000\000\000\000\250\340\051\230\000\000\200\040\000\000\206\104\322\000\020"},
    {308, "testlist_safe", 0, 5, states_52,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\200\040\000\000\206\104\322\000\000"},
    {309, "old_test", 0, 2, states_53,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\200\040\000\000\206\104\322\000\000"},
    {310, "old_lambdef", 0, 5, states_54,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\200\000\000\000\000\000\000\000\000"},
    {311, "test", 0, 6, states_55,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\200\040\000\000\206\104\322\000\000"},
    {312, "or_test", 0, 2, states_56,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\040\000\000\206\104\322\000\000"},
    {313, "and_test", 0, 2, states_57,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\040\000\000\206\104\322\000\000"},
    {314, "not_test", 0, 3, states_58,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\040\000\000\206\104\322\000\000"},
    {315, "comparison", 0, 2, states_59,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\206\104\322\000\000"},
    {316, "comp_op", 0, 4, states_60,
     "\000\000\000\000\000\000\000\000\000\000\000\100\000\000\000\040\377\000\000\000\000\000\000"},
    {317, "expr", 0, 2, states_61,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\206\104\322\000\000"},
    {318, "xor_expr", 0, 2, states_62,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\206\104\322\000\000"},
    {319, "and_expr", 0, 2, states_63,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\206\104\322\000\000"},
    {320, "shift_expr", 0, 2, states_64,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\206\104\322\000\000"},
    {321, "arith_expr", 0, 2, states_65,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\206\104\322\000\000"},
    {322, "term", 0, 2, states_66,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\206\104\322\000\000"},
    {323, "factor", 0, 3, states_67,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\206\104\322\000\000"},
    {324, "power", 0, 4, states_68,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\104\322\000\000"},
    {325, "atom_expr", 0, 3, states_69,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\104\322\000\000"},
    {326, "atom", 0, 11, states_70,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\100\322\000\000"},
    {327, "listmaker", 0, 5, states_71,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\200\040\000\000\206\104\322\000\000"},
    {328, "testlist_comp", 0, 5, states_72,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\200\040\000\000\206\104\322\000\000"},
    {329, "lambdef", 0, 5, states_73,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\200\000\000\000\000\000\000\000\000"},
    {330, "trailer", 0, 7, states_74,
     "\000\040\000\000\000\000\000\000\000\000\100\000\000\000\000\000\000\000\000\100\000\000\000"},
    {331, "subscriptlist", 0, 3, states_75,
     "\000\040\200\010\000\000\000\000\000\000\100\000\000\000\200\040\000\000\206\104\322\000\000"},
    {332, "subscript", 0, 7, states_76,
     "\000\040\200\010\000\000\000\000\000\000\100\000\000\000\200\040\000\000\206\104\322\000\000"},
    {333, "sliceop", 0, 3, states_77,
     "\000\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {334, "exprlist", 0, 3, states_78,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\206\104\322\000\000"},
    {335, "testlist", 0, 3, states_79,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\200\040\000\000\206\104\322\000\000"},
    {336, "dictorsetmaker", 0, 11, states_80,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\200\040\000\000\206\104\322\000\000"},
    {337, "classdef", 0, 8, states_81,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\040\000"},
    {338, "arglist", 0, 8, states_82,
     "\000\040\200\000\012\000\000\000\000\000\000\000\000\000\200\040\000\000\206\104\322\000\000"},
    {339, "argument", 0, 4, states_83,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\200\040\000\000\206\104\322\000\000"},
    {340, "list_iter", 0, 2, states_84,
     "\000\000\000\000\000\000\000\000\000\000\000\000\100\004\000\000\000\000\000\000\000\000\000"},
    {341, "list_for", 0, 6, states_85,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\000"},
    {342, "list_if", 0, 4, states_86,
     "\000\000\000\000\000\000\000\000\000\000\000\000\100\000\000\000\000\000\000\000\000\000\000"},
    {343, "comp_iter", 0, 2, states_87,
     "\000\000\000\000\000\000\000\000\000\000\000\000\100\004\000\000\000\000\000\000\000\000\000"},
    {344, "comp_for", 0, 6, states_88,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\000"},
    {345, "comp_if", 0, 4, states_89,
     "\000\000\000\000\000\000\000\000\000\000\000\000\100\000\000\000\000\000\000\000\000\000\000"},
    {346, "testlist1", 0, 2, states_90,
     "\000\040\200\000\000\000\000\000\000\000\000\000\000\000\200\040\000\000\206\104\322\000\000"},
    {347, "encoding_decl", 0, 2, states_91,
     "\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {348, "yield_expr", 0, 3, states_92,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\020"},
    {349, "yield_arg", 0, 3, states_93,
     "\000\040\200\000\000\000\000\000\000\000\040\000\000\000\200\040\000\000\206\104\322\000\000"},
};
static label labels[182] = {
    {0, "EMPTY"},
    {256, 0},
    {4, 0},
    {274, 0},
    {298, 0},
    {257, 0},
    {273, 0},
    {0, 0},
    {258, 0},
    {335, 0},
    {259, 0},
    {50, 0},
    {294, 0},
    {7, 0},
    {338, 0},
    {8, 0},
    {260, 0},
    {261, 0},
    {337, 0},
    {263, 0},
    {262, 0},
    {55, 0},
    {1, "def"},
    {1, 0},
    {264, 0},
    {3, "'->'"},
    {311, 0},
    {11, 0},
    {307, 0},
    {265, 0},
    {267, 0},
    {22, 0},
    {12, 0},
    {16, 0},
    {266, 0},
    {36, 0},
    {268, 0},
    {269, 0},
    {271, 0},
    {270, 0},
    {272, 0},
    {275, 0},
    {13, 0},
    {276, 0},
    {278, 0},
    {279, 0},
    {280, 0},
    {281, 0},
    {287, 0},
    {295, 0},
    {296, 0},
    {297, 0},
    {277, 0},
    {348, 0},
    {37, 0},
    {38, 0},
    {39, 0},
    {51, 0},
    {40, 0},
    {41, 0},
    {42, 0},
    {43, 0},
    {44, 0},
    {45, 0},
    {46, 0},
    {47, 0},
    {49, 0},
    {1, "print"},
    {35, 0},
    {1, "del"},
    {334, 0},
    {1, "pass"},
    {282, 0},
    {283, 0},
    {284, 0},
    {286, 0},
    {285, 0},
    {1, "break"},
    {1, "continue"},
    {1, "return"},
    {1, "raise"},
    {288, 0},
    {289, 0},
    {1, "import"},
    {293, 0},
    {1, "from"},
    {23, 0},
    {292, 0},
    {290, 0},
    {1, "as"},
    {291, 0},
    {1, "global"},
    {1, "exec"},
    {317, 0},
    {1, "in"},
    {1, "assert"},
    {300, 0},
    {301, 0},
    {302, 0},
    {303, 0},
    {304, 0},
    {299, 0},
    {1, "if"},
    {1, "elif"},
    {1, "else"},
    {1, "while"},
    {1, "for"},
    {1, "try"},
    {306, 0},
    {1, "finally"},
    {1, "with"},
    {305, 0},
    {1, "except"},
    {5, 0},
    {6, 0},
    {308, 0},
    {309, 0},
    {312, 0},
    {310, 0},
    {1, "lambda"},
    {329, 0},
    {313, 0},
    {1, "or"},
    {314, 0},
    {1, "and"},
    {1, "not"},
    {315, 0},
    {316, 0},
    {20, 0},
    {21, 0},
    {28, 0},
    {31, 0},
    {30, 0},
    {29, 0},
    {29, 0},
    {1, "is"},
    {318, 0},
    {18, 0},
    {319, 0},
    {33, 0},
    {320, 0},
    {19, 0},
    {321, 0},
    {34, 0},
    {322, 0},
    {14, 0},
    {15, 0},
    {323, 0},
    {17, 0},
    {24, 0},
    {48, 0},
    {32, 0},
    {324, 0},
    {325, 0},
    {54, 0},
    {326, 0},
    {330, 0},
    {328, 0},
    {9, 0},
    {327, 0},
    {10, 0},
    {26, 0},
    {336, 0},
    {27, 0},
    {25, 0},
    {346, 0},
    {2, 0},
    {3, 0},
    {341, 0},
    {344, 0},
    {331, 0},
    {332, 0},
    {333, 0},
    {1, "class"},
    {339, 0},
    {340, 0},
    {342, 0},
    {343, 0},
    {345, 0},
    {347, 0},
    {1, "yield"},
    {349, 0},
};
grammar _PyParser_Grammar = {
    94,
    dfas,
    {182, labels},
    256
};
